name: Tests

on:
  - push
  - pull_request

jobs:
  flake8_py3:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.11', '3.11.5']

    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        uses: tox